db:
  host: localhost
  port: 27017

spring:
  main:
    allow-bean-definition-overriding: true

web-filters:
  inject-user-id: true

security:
  enable: true
  allowed-origins:
    - ${frontend.dev.server}
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /v1/auth/signin
    - /v1/auth/signup
    - /v3/api-docs/**
    - /configuration/**
    - /swagger*/**
    - /webjars/**
    - /swagger-resources/**
    - /sw.js
  exposed-headers:
    - X-Xsrf-Token
  firebase-props:
    enable: true
    api-key: "${firebase-api-key}"
    account:
      type: "service_account"
      "project-id": "account-mi"
      "private-key-id": "${firebase-private-key-id}"
      "private-key": "${firebase-private-key}"
      "client-email": "${firebase-client-email}"
      "client-id": "109246710678736864849"
      "auth-uri": "https://accounts.google.com/o/oauth2/auth"
      "token-uri": "https://oauth2.googleapis.com/token"
      "auth-provider-cert-url": "https://www.googleapis.com/oauth2/v1/certs"
      "client-cert-url": "${firebase-client-cert-url}"