apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: account-mi-client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: account-mi-server-cluster-ip-service
              servicePort: 8080
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /?(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: account-mi-client-cluster-ip-service
#                port:
#                  number: 3000
#          - path: /api/?(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: account-mi-server-cluster-ip-service
#                port:
#                  number: 8080
